-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Pokemon.Query exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import Pokemon.InputObject
import Pokemon.Interface
import Pokemon.Object
import Pokemon.Scalar
import Pokemon.ScalarCodecs
import Pokemon.Union


query :
    SelectionSet decodesTo RootQuery
    -> SelectionSet (Maybe decodesTo) RootQuery
query object____ =
    Object.selectionForCompositeField "query" [] object____ (identity >> Decode.nullable)


type alias PokemonsRequiredArguments =
    { first : Int }


pokemons :
    PokemonsRequiredArguments
    -> SelectionSet decodesTo Pokemon.Object.Pokemon
    -> SelectionSet (Maybe (List (Maybe decodesTo))) RootQuery
pokemons requiredArgs____ object____ =
    Object.selectionForCompositeField "pokemons" [ Argument.required "first" requiredArgs____.first Encode.int ] object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


type alias PokemonOptionalArguments =
    { id : OptionalArgument String
    , name : OptionalArgument String
    }


pokemon :
    (PokemonOptionalArguments -> PokemonOptionalArguments)
    -> SelectionSet decodesTo Pokemon.Object.Pokemon
    -> SelectionSet (Maybe decodesTo) RootQuery
pokemon fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { id = Absent, name = Absent }

        optionalArgs____ =
            [ Argument.optional "id" filledInOptionals____.id Encode.string, Argument.optional "name" filledInOptionals____.name Encode.string ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "pokemon" optionalArgs____ object____ (identity >> Decode.nullable)
