-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Author exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


name : SelectionSet (Maybe String) Api.Object.Author
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


books :
    SelectionSet decodesTo Api.Object.Book
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.Author
books object____ =
    Object.selectionForCompositeField "books" [] object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
